version: "3.9"

services:
  nginx:
    container_name: nginx-custom-form
    image: nginx:latest
    ports:
      - 8902:80
      # - 8333:443 #if need ssl
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - phpfpm

  phpfpm:
    container_name: phpfpm-custom-form
    build: ./docker/php/
    volumes:
      - .:/var/www
      - ./docker/php/configs:/usr/local/etc/php/conf.d
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    container_name: mysql-custom-form
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    restart: always
    working_dir: /app
    volumes:
      - .data:/usr/data
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=custom-form
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3200:3306"
